export enum TaskType {
	IMPORTANT_AND_URGENT = 'IMPORTANT_AND_URGENT',
  IMPORTANT_AND__NOT_URGENT = 'IMPORTANT_AND_NOT_URGENT',
  NOT_IMPORTANT_AND_URGENT = 'NOT_IMPORTANT_AND_URGENT',
  NOT_IMPORTANT_AND_NOT_URGENT = 'NOT_IMPORTANT_AND_NOT_URGENT',
}